name: Build and deploy React app to Azure Web App - sugarlab-frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - run: |
          cd frontend
          npm install
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'sugarlab-frontend'
          slot-name: 'Production'
          package: build
